// if try are throw the arrow just after it is goint to  catch scope and it will be execute 
try{
    console.log("hello");
    console.log(a);
}catch{
   console.log("A is not defined");
}finally{
    console.log("Error Handiling");
}

// finally always execute neither try nor cath will be effectedf


